name = "Rates"
uuid = "84e8744e-4c48-11e9-33f6-2d4803e638bd"
authors = ["Felipe Noronha <felipenoris@gmail.com>"]
version = "0.0.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]

